spring:
  application:
    name: han-note-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: 192.168.1.117:8848
        namespace: 6274668c-88bc-4fe9-a8b4-5e52063030b2
        group: DEFAULT_GROUP
        file-extension: yaml
        username: nacos
        password: nacos
        refresh-enabled: true
      discovery:
        server-addr: 192.168.1.117:8848
        namespace: 6274668c-88bc-4fe9-a8b4-5e52063030b2
        group: DEFAULT_GROUP
        enabled: true
        username: nacos
        password: nacos
  config:
    import:
      - nacos:han-note-common-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:han-note-db-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:han-note-sa-token-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
