-- 创建表
CREATE TABLE t_user
(
    id             BIGSERIAL PRIMARY KEY,                          -- 使用 BIGSERIAL 实现自增，且自带索引
    hannote_id     VARCHAR(15) NOT NULL,
    password       VARCHAR(64),
    nickname       VARCHAR(24) NOT NULL,
    avatar         VARCHAR(120),
    birthday       DATE,
    background_img VARCHAR(120),
    phone          VARCHAR(11) NOT NULL,
    sex            SMALLINT             DEFAULT 0,                 -- PG 习惯用 SMALLINT 代替 tinyint
    status         SMALLINT    NOT NULL DEFAULT 0,
    introduction   VARCHAR(100),
    create_time    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP, -- PG 使用 TIMESTAMP
    update_time    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,             -- PG 有原生布尔类型，比 bit(1) 更易用

    -- 约束命名规范
    CONSTRAINT uk_hannote_id UNIQUE (hannote_id),
    CONSTRAINT uk_phone UNIQUE (phone)
);

-- PostgreSQL 的注释需要独立语句执行
COMMENT ON TABLE t_user IS '用户表';
COMMENT ON COLUMN t_user.id IS '主键ID';
COMMENT ON COLUMN t_user.hannote_id IS '小憨书号(唯一凭证)';
COMMENT ON COLUMN t_user.password IS '密码';
COMMENT ON COLUMN t_user.nickname IS '昵称';
COMMENT ON COLUMN t_user.avatar IS '头像';
COMMENT ON COLUMN t_user.birthday IS '生日';
COMMENT ON COLUMN t_user.background_img IS '背景图';
COMMENT ON COLUMN t_user.phone IS '手机号';
COMMENT ON COLUMN t_user.sex IS '性别(0：女 1：男)';
COMMENT ON COLUMN t_user.status IS '状态(0：启用 1：禁用)';
COMMENT ON COLUMN t_user.introduction IS '个人简介';
COMMENT ON COLUMN t_user.create_time IS '创建时间';
COMMENT ON COLUMN t_user.update_time IS '更新时间';
COMMENT ON COLUMN t_user.deleted IS '逻辑删除(false：未删除 true：已删除)';

-- 1. 角色表
CREATE TABLE "t_role"
(
    "id"          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "role_name"   varchar(32) NOT NULL,
    "role_key"    varchar(32) NOT NULL,
    "status"      smallint    NOT NULL DEFAULT 0,
    "sort"        integer     NOT NULL DEFAULT 0,
    "remark"      varchar(255),
    "create_time" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"  boolean     NOT NULL DEFAULT false
);

CREATE UNIQUE INDEX "uk_role_key" ON "t_role" ("role_key");
COMMENT ON TABLE "t_role" IS '角色表';
COMMENT ON COLUMN "t_role"."id" IS '主键ID';
COMMENT ON COLUMN "t_role"."role_name" IS '角色名';
COMMENT ON COLUMN "t_role"."role_key" IS '角色唯一标识';
COMMENT ON COLUMN "t_role"."status" IS '状态(0：启用 1：禁用)';
COMMENT ON COLUMN "t_role"."sort" IS '管理系统中的显示顺序';
COMMENT ON COLUMN "t_role"."deleted" IS '逻辑删除';

-- 2. 权限表
CREATE TABLE "t_permission"
(
    "id"             bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "parent_id"      bigint       NOT NULL DEFAULT 0,
    "name"           varchar(16)  NOT NULL,
    "type"           smallint     NOT NULL, -- 1：目录 2：菜单 3：按钮
    "menu_url"       varchar(32)  NOT NULL DEFAULT '',
    "menu_icon"      varchar(255) NOT NULL DEFAULT '',
    "sort"           integer      NOT NULL DEFAULT 0,
    "permission_key" varchar(64)  NOT NULL,
    "status"         smallint     NOT NULL DEFAULT 0,
    "create_time"    timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"    timestamptz  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"     boolean      NOT NULL DEFAULT false
);

COMMENT ON TABLE "t_permission" IS '权限表';

-- 3. 用户角色关联表
CREATE TABLE "t_user_role_rel"
(
    "id"          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "user_id"     bigint      NOT NULL,
    "role_id"     bigint      NOT NULL,
    "create_time" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"  boolean     NOT NULL DEFAULT false
);

CREATE INDEX "idx_ur_user_id" ON "t_user_role_rel" ("user_id");
CREATE INDEX "idx_ur_role_id" ON "t_user_role_rel" ("role_id");
COMMENT ON TABLE "t_user_role_rel" IS '用户角色关联表';

-- 4. 角色权限关联表
CREATE TABLE "t_role_permission_rel"
(
    "id"            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "role_id"       bigint      NOT NULL,
    "permission_id" bigint      NOT NULL,
    "create_time"   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "update_time"   timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted"    boolean     NOT NULL DEFAULT false
);

CREATE INDEX "idx_rp_role_id" ON "t_role_permission_rel" ("role_id");
CREATE INDEX "idx_rp_permission_id" ON "t_role_permission_rel" ("permission_id");
COMMENT ON TABLE "t_role_permission_rel" IS '角色权限关联表';